version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: many_notes_postgres
    environment:
      POSTGRES_DB: many_notes
      POSTGRES_USER: many_notes
      POSTGRES_PASSWORD: many_notes_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U many_notes"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 